# Generated by Django 6.0.7 on 2026-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('publishdate', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
